# docker/dev/docker-compose.ci.yaml
# Copy dari docker-compose.yaml lo, cuma buang frontend & monitoring

services:
  database-mysql:
    image: mysql:8.0
    container_name: database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iamra_course_test  # Database buat testing
    ports:
      - "3307:3306"
    networks:
      - iamra_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      timeout: 10s

  database-redis:
    image: redis:latest
    container_name: database-redis
    ports:
      - "6379:6379"
    networks:
      - iamra_net

  database-mongo:
    image: mongo:latest
    container_name: database-mongo
    ports:
      - "27017:27017"
    networks:
      - iamra_net

  # Copy persis dari docker-compose.yaml lo
  backend-api-user:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/user/Dockerfile.api-user
    container_name: backend-api-user
    volumes:
      - "../../backend-api-user:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    # Environment dari file yang dibuat di workflow
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net

  backend-api-student:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/student/Dockerfile.api-student
    container_name: backend-api-student
    volumes:
      - "../../backend-api-student:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-student/.env"
    networks:
      - iamra_net

  backend-api-instructor:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/instructor/Dockerfile.api-instructor
    container_name: backend-api-instructor
    volumes:
      - "../../backend-api-instructor:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-instructor/.env"
    networks:
      - iamra_net

  backend-api-forum:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/forum/Dockerfile.api-forum
    container_name: backend-api-forum
    volumes:
      - "../../backend-api-forum:/app"
    depends_on:
      - backend-api-user
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-forum/.env"
    networks:
      - iamra_net

  backend-api-public:
    build:
      context: ../../
      dockerfile: docker/dev/backend-laravel/public/Dockerfile.api-public
    container_name: backend-api-public
    volumes:
      - "../../backend-api-public:/app"
    depends_on:
      database-mysql:
        condition: service_healthy
      database-redis:
        condition: service_started
      database-mongo:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-public/.env"
    networks:
      - iamra_net

networks:
  iamra_net:
    driver: bridge