<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Http;
use Tests\utils\Repository;

abstract class TestCase extends BaseTestCase
{
    public string $token;
    public string $url;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Repository::initData();
        $this->url = config('api.version');
        $res = Http::post('http://backend-api-user/user-api/v1/auth/login', [
            'username' => Repository::USERNAME,
            'password' => Repository::PASSWORD
        ]);

        $cookies = $res->header('Set-Cookie');
        if (! $cookies || !preg_match('/access_token=([^;]+)/', $cookies, $matches)) {
            throw new \RuntimeException("Failed to get access_token from login response");
        }

        $this->token = $matches[1];
    }

    protected function tearDown(): void
    {
        Repository::clearData();
        parent::tearDown();
    }
}
