# docker-compose.yaml
services:
  server-nginx:
    image: nginx:alpine
    container_name: server-nginx
    ports:
      - "80:80"
    volumes:
      - "./server-entrypoint/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../../frontend-forum/dist:/var/www/html/forum:ro"
      - "../../frontend-instructor/dist:/var/www/html/instructor:ro"
      - "../../frontend-public/dist:/var/www/html/public:ro"
      - "../../frontend-student/dist:/var/www/html/student:ro"
      - "../../frontend-user/dist:/var/www/html/user:ro"
    depends_on:
      - backend-api-forum
      - backend-api-instructor
      - backend-api-public
      - backend-api-student
      - backend-api-user
    networks:
      - iamra_net

  backend-api-instructor:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/instructor/Dockerfile.api-instructor
    container_name: backend-api-instructor
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-instructor/.env"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  backend-api-public:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/public/Dockerfile.api-public
    container_name: backend-api-public
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-public/.env"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  backend-api-student:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/student/Dockerfile.api-student
    container_name: backend-api-student
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-student/.env"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  backend-api-user:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/user/Dockerfile.api-user
    container_name: backend-api-user
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  backend-api-user-reverb:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/user/Dockerfile.api-user-reverb
    container_name: backend-api-user-reverb
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  backend-api-user-queue:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/user/Dockerfile.api-user-queue
    container_name: backend-api-user-queue
    ports:
      - "9595:80"
    depends_on:
      - backend-api-user
      - database-redis
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-user/.env"
    networks:
      - iamra_net
    mem_limit: 256m
    cpus: 0.25

  backend-api-forum:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/forum/Dockerfile.api-forum
    container_name: backend-api-forum
    depends_on:
      - backend-api-user
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-forum/.env"
    networks:
      - iamra_net
    ports:
      - "9000:6001"
    mem_limit: 512m
    cpus: 0.25

  backend-api-forum-reverb:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/forum/Dockerfile.api-forum-reverb
    container_name: backend-api-forum-reverb
    depends_on:
      database-redis:
        condition: service_started
    env_file:
      - "backend-laravel/_shared/.env.shared"
      - "../../backend-api-forum/.env"
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  frontend-user:
    build:
      context: ../../
      dockerfile: docker/prod/frontend-react/Dockerfile
    container_name: frontend-user
    volumes:
      - "../../frontend-user:/app"
      - "./frontend-react/.env.shared:/app/.env"
    environment:
      - VITE_CLIENT_GOOGLE=501957692849-nprqfdeclrvjseadfs3bpru3arci95eg.apps.googleusercontent.com
      - VITE_API_KEY_OPEN_CAGE_DATA=1c364950870b42049cebeb19d1669abe
    depends_on:
      - backend-api-user
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  frontend-instructor:
    build:
      context: ../../
      dockerfile: docker/prod/frontend-react/Dockerfile
    container_name: frontend-instructor
    volumes:
      - "../../frontend-instructor:/app"
      - "./frontend-react/.env.shared:/app/.env"
    depends_on:
      - backend-api-instructor
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  frontend-student:
    build:
      context: ../../
      dockerfile: docker/prod/frontend-react/Dockerfile
    container_name: frontend-student
    volumes:
      - "../../frontend-student:/app"
      - "./frontend-react/.env.shared:/app/.env"
    depends_on:
      - backend-api-student
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  frontend-public:
    build:
      context: ../../
      dockerfile: docker/prod/frontend-react/Dockerfile
    container_name: frontend-public
    volumes:
      - "../../frontend-public:/app"
      - "./frontend-react/.env.shared:/app/.env"
    depends_on:
      - backend-api-public
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  frontend-forum:
    build:
      context: ../../
      dockerfile: docker/prod/frontend-react/Dockerfile
    container_name: frontend-forum
    volumes:
      - "../../frontend-forum:/app"
      - "./frontend-react/.env.shared:/app/.env"
    depends_on:
      - backend-api-forum
    networks:
      - iamra_net
    mem_limit: 512m
    cpus: 0.25

  database-redis:
    image: redis:latest
    container_name: database-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - iamra_net
    mem_limit: 128m
    cpus: 0.10

volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data

networks:
  iamra_net:
    name: iamra_net
    driver: bridge
